management:
  endpoints:
    web:
      exposure:
        include: "*"

jjwt:
  secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
  expiration: 28800
  password:
    encoder:
      secret: mysecret
      iteration: 33
      keylength: 256
